server:
  port: 9999

spring:
  cloud:
    nacos:
      discovery:                                     # nacos注册服务
        namespace: dev                               # 命名空间
        server-addr: 124.221.233.62:8848             # nacos地址
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        register-enabled: true
      username: nacos
      password: nacos

