server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery:                                     # nacos注册服务
        namespace: dev                               # 命名空间
        server-addr: 47.113.216.179:8848             # nacos地址
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        register-enabled: true
      username: nacos
      password: nacos


#spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#  jackson:
#    default-property-inclusion: always
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 12345678
#    url: jdbc:mysql://localhost:3306/db_smart_iot
#
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 5000      #连接超时，单位毫秒
#    lettuce:
#      pool:
#        max-active: 8  #连接池最大连接数（使用负数表示没有限制） 默认为 8
#        max-wait: -1   #连接池最大等待时间（使用负数表示没有限制） 默认-1
#        max-idle: 8    #连接池最大空闲链接 默认为 8
#        min-idle: 0     #连接池中最小空闲链接 默认0
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
##debug: true
#
## MinIO配置
#minio:
#  # 服务端ip
#  endpoint: http://47.113.216.179:9000
#  # 图片bucket
#  bucket: smart-iot
#  # 访问用户名
#  access-key: minioadmin
#  # 访问密码
#  secret-key: minioadmin